/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clockthread;

import java.io.IOException;
import java.io.ObjectOutputStream;
import static java.lang.Thread.sleep;
import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mispan
 */
public class Client extends javax.swing.JFrame {

    private volatile boolean isRun = true;
    private Socket socket;
    private ObjectOutputStream oos;
    private boolean connected = false;

    private Thread thread = new Thread() {
        public void run() {
            try {
                socket = new Socket("localhost", 1999);
                oos = new ObjectOutputStream(socket.getOutputStream());
                connected = true;
            } catch (Exception e) {
            }

            while (true) {
                allowPause();
                Calendar c = Calendar.getInstance();
                DateFormat dateFormat = new SimpleDateFormat("EEEEE, dd MMMM yyyy");
                DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");

                dateTxt.setText(dateFormat.format(c.getTime()));
                timeTxt.setText(timeFormat.format(c.getTime()));

                try {
                    sleep(50);
                    if (connected) {
                        oos.writeObject(c);
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    };

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();

        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timeTxt = new javax.swing.JLabel();
        dateTxt = new javax.swing.JLabel();
        contolBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 0, 0));

        timeTxt.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        timeTxt.setForeground(new java.awt.Color(255, 102, 0));
        timeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clockthread/002-clock.png"))); // NOI18N
        timeTxt.setText("time");
        timeTxt.setToolTipText("");
        timeTxt.setPreferredSize(new java.awt.Dimension(100, 50));

        dateTxt.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        dateTxt.setForeground(new java.awt.Color(255, 102, 0));
        dateTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTxt.setIcon(new javax.swing.ImageIcon("E:\\MATERI KULIAH\\semester 5\\Pemrograman Jaringan\\png\\001-calendar.png")); // NOI18N
        dateTxt.setText("date");
        dateTxt.setToolTipText("");

        contolBtn.setBackground(new java.awt.Color(204, 51, 0));
        contolBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contolBtn.setForeground(new java.awt.Color(51, 0, 0));
        contolBtn.setText("Pause");
        contolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contolBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contolBtn)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contolBtnActionPerformed
        isRun = !isRun;
        synchronized (thread) {
            thread.notifyAll();
        }
        contolBtn.setText((!isRun) ? "Resume" : "Pause");
    }//GEN-LAST:event_contolBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contolBtn;
    private javax.swing.JLabel dateTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel timeTxt;
    // End of variables declaration//GEN-END:variables

    private void allowPause() {
        synchronized (thread) {
            while (!isRun) {
                try {
                    thread.wait();
                } catch (InterruptedException ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                }
            };
        }
    }
}
